### ISSUE TITLE
Link to ocamldoc in README is broken

### ISSUE THREAD

**Issue by mars0i** [vbmithr/ocaml-msgpck#5]
The link in this text

> The documentation and API reference is automatically generated by ocamldoc from the interfaces. It can be consulted online and there is a generated version in the doc directory of the distribution.

is broken

**Comment by c-cube** [comment]
should use odoc now, right? :)

**Comment by vbmithr** [comment]
Yeah, `ocamldoc` is old story. Removed the section from the readme ;)
